//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Facultad = new HashSet<Facultad>();
            this.Alumno = new HashSet<Alumno>();
        }
    
        public int ID_Ciudad { get; set; }
        public string nombre { get; set; }
        public int estado { get; set; }
    
        public virtual Estado Estado1 { get; set; }
        public virtual ICollection<Facultad> Facultad { get; set; }
        public virtual ICollection<Alumno> Alumno { get; set; }
    }
}
