//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }
    
        public int ID_Estado { get; set; }
        public string nombre { get; set; }
        public int pais { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual Pais Pais1 { get; set; }
    }
}
