//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.MateriaAlumno = new HashSet<MateriaAlumno>();
        }
    
        public int ID_Materia { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<MateriaAlumno> MateriaAlumno { get; set; }
    }
}
